### ISSUE TITLE
Procedure to Run Sessa?

### ISSUE THREAD

**Issue by prasanthhs** [dice-group/SESSA#10]
Can you please update README?  Currently we want to add a web service to Sessa. But we always get NULL pointer exception due to dictionary currently not being present. 

There is no procedure that mentions how do we add dictionary to Sessa. 
(test_1.nt and test_2.ttl are used to test RdfDictionaryImport.java that loads RDF to SESSA.)->Where is RDFDictionaryImport.java or test_1 and test_2? We cannot find it under Sessa.

**Comment by SiC42** [comment]
I updated the README. Hopefully this helps you enough to get started.
You can also look into the SESSAMeasurement class, as it uses SESSA to measure it on the QALD-questions.

**Comment by prasanthhs** [comment]
Thank you for your update. This part was already clear to me and we had done the same(called checkDictionary() of SESSAMeasurement in our main()). I wanted to know about the input files and where we can find them. If you have any simplified files those are better as well.

**Comment by SiC42** [comment]
If you just want to test your webservice with small files, try to use the test files in "src/test/resources/".

_en_surface_forms_small.tsv_ can answer some questions, which you can find in "src/test/java/org/aksw/sessa/main/SESSATest.java"
