### ISSUE TITLE
SelfbuildingGraph cannot handle interlinking in already existing nodes

### ISSUE THREAD

**Issue by SiC42** [dice-group/SESSA#11]
As of now, if the "missing triplet" for two URIs is already in the current graph (because it was the missing triplet for two other URIs), the process will be ignored and no new fact node will be created.

Simplified example on how it could be:
![image](https://user-images.githubusercontent.com/7562025/33991891-d0519a30-e0d0-11e7-8a08-08f5472fa896.png)

**Comment by RicardoUsbeck** [comment]
Can you explain a bit more the difference between the current and the desired graph state?

**Comment by SiC42** [comment]
The simplified example shows the desired state.
For the current state:
Let's say _Lion\_King\_(musical)_ was found by _musicBy_ and _Elton\_John_. So the upper part of the image is already created.
Now, if SelfBuildingGraph finds _Lion\_King\_(musical)_ for _type_ and _Musical_, it checks if the node is already present and skips it. Therefore, the lower fact-node will not be created.

I'm not sure how this bug was created. Probably because I was under the impression that only newly created nodes can be the "answer".
