### ISSUE TITLE
Color Update-Problem with Multiple Nodes Pointing to one Answer 

### ISSUE THREAD

**Issue by SiC42** [dice-group/SESSA#18]
![image](https://user-images.githubusercontent.com/7562025/35167259-15af06bc-fd55-11e7-98d3-9c285cc06f9d.png)

The picture illustrates one simplified example.
Because "language" is a descendant of "offical language" in the n-gram hierarchy, the color of "language" (orange) is (as per definition) a descendant of the color of "offical language" (red).

First the fact nodes get the right colors they should have.
Then for the node "Dutch" it is checked, if the colors of all the neighbors (the two fact nodes) are not related, i.e. if there a no descendants to another color.
Because orange is a descandant of red, "Dutch" is not allowed to update.

**Comment by SiC42** [comment]
Possible solution:
Instead of updating the colors after each round of searching for new nodes, update the nodes immediatly.
However, this is probably a bigger rework

**Comment by RicardoUsbeck** [comment]
How about given the node the color of the highest explanation score?

**Comment by SiC42** [comment]
Yes, this should happen.
I already started the fix in branch bugfix/updateColoringProblem, which seems to solve the issue. However, I still need to make tests for the new methods and document it

**Comment by SiC42** [comment]
Fixed in 47d781d857991149bb6eb625db6a14d65dc5c568
