### ISSUE TITLE
Make dockerfile for SESSA

### ISSUE THREAD

**Issue by SiC42** [dice-group/SESSA#30]

**Comment by yamalight** [comment]
Running `mvn install` fails for me with following error:
```
[ERROR] Failed to execute goal on project KeywordSearch: Could not resolve dependencies for project org.dbpedia:KeywordSearch:jar:0.0.1: Could not find artifact org.dice-research:gerbilQABencmarkingTemplate:jar:0.0.1-SNAPSHOT in mvnrepository (http://www.mvnrepository.com/) -> [Help 1]
```

**Comment by SiC42** [comment]
See Requirements in Readme:

>Because SESSA contains a web-service which builds onto the GerbilQA-Benchmarking-Template, you also have install the GerbilQA-Benchmarking-Template first.

>>git clone https://github.com/dice-group/GerbilQA-Benchmarking-Template.git
cd GerbilQA-Benchmarking-Template
mvn clean install

I didn't want to throw the jar into the repo

**Comment by yamalight** [comment]
can we publish that jar on our maven repo and grab it from there?
otherwise dockerizing the project "as is" will be quite a mess.

**Comment by RicardoUsbeck** [comment]
It is now in our repo http://maven.aksw.org/archiva/#artifact/org.dice-research/gerbilQABencmarkingTemplate

can you try again mvn install?

**Comment by yamalight** [comment]
works now, thanks!

next question: is there a simple way to package the app to jar and run it from jar?

**Comment by SiC42** [comment]
1. "mvn clean package" should produce KeywordSearch-0.0.1-bootable-with-spring.jar in the target folder. This should be executable with java -jar target/KeywordSearch-0.0.1-bootable-with-spring.jar
2. Unfortunately It is hardcoded for now

Another question:
Will you be able to provide the two files mentioned in the Readme?
>cd src/main
mkdir resources
cd resources
wget downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt
wget downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2
bunzip2 labels_en.ttl.bz2

**Comment by yamalight** [comment]
OK, got it. I'll download the files into resources for now. 
But in the long run it'd be better to allow specifying path to them instead of hardcoding/forcing them into resources.

**Comment by yamalight** [comment]
OK, build succeeds, but I get the errors when I start the app and it doesn't seem to work
I've attached the execution log.
[sessa.log](https://github.com/dice-group/SESSA/files/1837894/sessa.log)

**Comment by SiC42** [comment]
I hopefully fixed that bug now. If not, can you push your build into a new branch and i will try to fix it?

**Comment by yamalight** [comment]
Still fails, but with different error. See log attached: 
[sessa.log](https://github.com/dice-group/SESSA/files/1838297/sessa.log)

**Comment by SiC42** [comment]
It seems to be the same problem
>Caused by: org.apache.jena.riot.RiotException: Producer failed to ever call start(), declaring producer dead

I can't reproduce it via the jar. Is Multithreading not allowed or something?

I could reroll the changes I made in RdfFileHandler (which is where the error occurs), but then the application will need a lot of memory (~10GB for parsing the big TTL-file)

**Comment by yamalight** [comment]
@SiC42 I'm running the built jar in the `openjdk:8` docker image (you can see full env for it [here](https://github.com/docker-library/openjdk/blob/1506887e16eba85b37dcf0a5ff8c9c2abe3fa9b7/8-jdk/Dockerfile)). I haven't specifically disabled multithreading, so it should be working, right?
Additionally I pass `JAVA_OPTS="-Xmx2G"` as a flag. Is that not enough?

**Comment by SiC42** [comment]
I think I have reproduced it by deleting the files it tries to use.
is the file "src/main/resources/dbpedia_3Eng_class.ttl" missing?

**Comment by yamalight** [comment]
@SiC42 Oh, I just noticed - running the fetching from README, i.e.:
```
wget downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt
wget downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2
bunzip2 labels_en.ttl.bz2
```
Only results in two files: `dbpedia_2016-10.nt` and `labels_en.ttl`. 
There's no `dbpedia_3Eng_class.ttl` - where do I get it?

**Comment by SiC42** [comment]
I'm sorry I did not have much experience with maven before this and therefore did not know that this was possible. Give this weekend and I will implement it.

To your second post: I thought they were part of the repo. The **two** missing files are part of [HAWK](https://github.com/dice-group/NLIWOD/tree/master/qa.hawk/resources). I will add that to the Readme

**Comment by yamalight** [comment]
@SiC42 we can just do the basic version for now without packaging. just ping me once you describe how to get all required files.

**Comment by SiC42** [comment]
@yamalight done. See Readme

**Comment by yamalight** [comment]
Dockerfile has been added, resulting image seems to work fine.
I've also setup [autobuild on docker hub](https://hub.docker.com/r/dicegroup/sessa/), docker image will be accessible via `docker run dicegroup/sessa` once build is finished.
